-- PostgreSQL
-- 用户表
DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user
(
    id             int8 generated by default as identity primary key,
    name           varchar,                   -- '用户名称',
    alias          varchar,                   --   '别名',
    tel            varchar,                   --, '手机号码',
    sex            varchar,                   -- '性别',
    birthday       varchar,                   -- '生日',
    address        varchar,                   -- '地址',
    card_no        varchar,                   -- '证件号',
    card_type      varchar,                   -- '证件类型',
    avatar         varchar,                   -- '头像',
    login_name     varchar   not null unique, -- '登录账号（唯一约束）',
    login_password varchar   not null,        -- '登录密码',
    create_time    timestamp not null,        -- '创建时间',
    update_time    timestamp not null,        -- '最近更新时间',
    is_frozen      boolean                    -- '是否冻结'
);
comment on table sys_user is '用户表';
comment on column sys_user.name is '用户名称';
comment on column sys_user.alias is '别名';
comment on column sys_user.tel is '手机号码';
comment on column sys_user.sex is '性别';
comment on column sys_user.birthday is '生日';
comment on column sys_user.address is '地址';
comment on column sys_user.card_no is '证件号';
comment on column sys_user.card_type is '证件类型';
comment on column sys_user.avatar is '头像';
comment on column sys_user.login_name is '登录账号（唯一约束）';
comment on column sys_user.login_password is '登录密码';
comment on column sys_user.is_frozen is '是否冻结';
comment on column sys_user.create_time is '创建时间';
comment on column sys_user.update_time is '最近更新时间';


-- 角色表
DROP TABLE IF EXISTS sys_role;
CREATE TABLE sys_role
(
    id          int8 generated by default as identity primary key,
    name        varchar   not null unique, -- '角色',
    description varchar,                   -- '描述',
    create_time timestamp not null,        -- '创建时间',
    update_time timestamp not null         -- '最近更新时间'
);
comment on table sys_role is '角色表';
comment on column sys_role.name is '角色';
comment on column sys_role.description is '描述';
comment on column sys_role.create_time is '创建时间';
comment on column sys_role.update_time is '最近更新时间';

begin;
insert into sys_role
values (0, 'admin', '管理员', now(), now()),
       (1, 'default', '普通用户', now(), now());
commit;


-- 用户角色关系表
DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE sys_user_role
(
    id          int8 generated by default as identity primary key,
    role_id     int8      not null, -- '角色ID',
    user_id     int8      not null, -- '用户ID',
    create_time timestamp not null, -- '创建时间',
    update_time timestamp not null  -- '最近更新时间'
);
comment on table sys_user_role is '用户角色关系表';
comment on column sys_user_role.role_id is '角色ID';
comment on column sys_user_role.user_id is '用户ID';
comment on column sys_user_role.create_time is '创建时间';
comment on column sys_user_role.update_time is '最近更新时间';


-- 权限表（URL路径，访问方式控制）
DROP TABLE IF EXISTS sys_permission;
CREATE TABLE sys_permission
(
    id          int8 generated by default as identity primary key,
    url         varchar   not null,            -- '资源路径（支持/*一级匹配、/**多级匹配）',
    http_method varchar   not null,            -- '请求类型（类型为 HttpMethod，支持 * 匹配所有）',
    description varchar   not null,            -- '描述信息',
    category    varchar   not null,            -- '分类类别',
    ordered     int4      not null default 99, -- '排序，越小越靠前',
    create_time timestamp not null,            -- '创建时间',
    update_time timestamp not null             -- '最近更新时间'
);
comment on table sys_permission is '权限表（URL路径，访问方式控制）';
comment on column sys_permission.url is '资源路径（支持/*一级匹配、/**多级匹配）';
comment on column sys_permission.http_method is '请求类型（类型为 HttpMethod，支持 * 匹配所有）';
comment on column sys_permission.description is '描述信息';
comment on column sys_permission.category is '分类类别';
comment on column sys_permission.ordered is '排序，越小越靠前';
comment on column sys_permission.create_time is '创建时间';
comment on column sys_permission.update_time is '最近更新时间';


-- 权限角色关系表
DROP TABLE IF EXISTS sys_role_permission;
CREATE TABLE sys_role_permission
(
    id            int8 generated by default as identity primary key,
    permission_id int8      not null, -- '权限ID',
    role_id       int8      not null, -- '角色ID',
    create_time   timestamp not null, -- '创建时间',
    update_time   timestamp not null  -- '最近更新时间'
);
comment on table sys_role_permission is '权限角色关系表';
comment on column sys_role_permission.permission_id is '权限ID';
comment on column sys_role_permission.role_id is '角色ID';
comment on column sys_role_permission.create_time is '创建时间';
comment on column sys_role_permission.update_time is '最近更新时间';


-- 数据权限表
DROP TABLE IF EXISTS sys_data_permission;
CREATE TABLE sys_data_permission
(
    id          int8 generated by default as identity primary key,
    url         varchar   not null,            -- '资源路径（支持/*一级匹配、/**多级匹配）',
    http_method varchar   not null,            -- '请求类型（类型为 HttpMethod，支持 * 匹配所有）',
    permission  varchar   not null,            -- '数据权限',
    description varchar   not null,            -- '描述信息',
    category    varchar   not null,            -- '分类类别',
    ordered     int4      not null default 99, -- '排序，越小越靠前',
    create_time timestamp not null,            -- '创建时间',
    update_time timestamp not null             -- '最近更新时间'
);
comment on table sys_data_permission is '数据权限表';
comment on column sys_data_permission.url is '资源路径（支持/*一级匹配、/**多级匹配）';
comment on column sys_data_permission.http_method is '请求类型（类型为 HttpMethod，支持 * 匹配所有）';
comment on column sys_data_permission.permission is '数据权限';
comment on column sys_data_permission.description is '描述信息';
comment on column sys_data_permission.category is '分类类别';
comment on column sys_data_permission.ordered is '排序，越小越靠前';
comment on column sys_data_permission.create_time is '创建时间';
comment on column sys_data_permission.update_time is '最近更新时间';


-- 数据权限角色关系表
DROP TABLE IF EXISTS sys_role_data_permission;
CREATE TABLE sys_role_data_permission
(
    id            int8 generated by default as identity primary key,
    permission_id int8      not null, -- '数据权限ID',
    role_id       int8      not null, -- '角色ID',
    create_time   timestamp not null, -- '创建时间',
    update_time   timestamp not null  -- '最近更新时间'
);
comment on table sys_role_data_permission is '数据权限角色关系表';
comment on column sys_role_data_permission.permission_id is '数据权限ID';
comment on column sys_role_data_permission.role_id is '角色ID';
comment on column sys_role_data_permission.create_time is '创建时间';
comment on column sys_role_data_permission.update_time is '最近更新时间';


-- 部门表
DROP TABLE IF EXISTS sys_department;
CREATE TABLE sys_department
(
    id          int8 generated by default as identity primary key,
    parent_id   int8      not null default 0, -- '上级部门（0标识没有上级）',
    name        varchar   not null unique,    -- '部门名称',
    description varchar,                      -- '部门描述',
    create_time timestamp not null,           -- '创建时间',
    update_time timestamp not null            -- '最近更新时间'
);
comment on table sys_department is '部门表';
comment on column sys_department.parent_id is '上级部门（0标识没有上级）';
comment on column sys_department.name is '部门名称';
comment on column sys_department.description is '部门描述';
comment on column sys_department.create_time is '创建时间';
comment on column sys_department.update_time is '最近更新时间';


-- 用户部门表
DROP TABLE IF EXISTS sys_department_user;
CREATE TABLE sys_department_user
(
    id            int8 generated by default as identity primary key,
    user_id       int8      not null, -- '用户ID',
    department_id int8      not null, -- '部门',
    create_time   timestamp not null, -- '创建时间',
    update_time   timestamp not null  -- '最近更新时间'
);
comment on table sys_department_user is '用户部门表';
comment on column sys_department_user.user_id is '用户ID';
comment on column sys_department_user.department_id is '部门';
comment on column sys_department_user.create_time is '创建时间';
comment on column sys_department_user.update_time is '最近更新时间';


-- 前端菜单表（内容设计为前端要求）
DROP TABLE IF EXISTS sys_menu;
CREATE TABLE sys_menu
(
    id           int8 generated by default as identity primary key,
    parent_id    int8      not null default 0, -- 上级菜单ID
    name         varchar,                      -- 菜单名称
    project_name varchar,                      -- 项目名称
    icon         varchar,                      -- 图标
    path         varchar,                      -- 路径
    sort         int4,                         -- 排序
    keep_alive   varchar,                      -- 缓存
    type         varchar,                      -- 菜单类型
    permission   varchar,                      -- 权限字段
    create_time  timestamp not null,           -- '创建时间',
    update_time  timestamp not null            -- '最近更新时间'
);
comment on table sys_menu is '前端菜单表（内容设计为前端要求）';
comment on column sys_menu.parent_id is '上级菜单ID';
comment on column sys_menu.name is '菜单名称';
comment on column sys_menu.project_name is '项目名称';
comment on column sys_menu.icon is '图标';
comment on column sys_menu.path is '路径';
comment on column sys_menu.sort is '排序';
comment on column sys_menu.keep_alive is '缓存';
comment on column sys_menu.type is '菜单类型';
comment on column sys_menu.permission is '权限字段';
comment on column sys_menu.create_time is '创建时间';
comment on column sys_menu.update_time is '最近更新时间';


-- 前端菜单接口权限关联表
DROP TABLE IF EXISTS sys_menu_permission;
CREATE TABLE sys_menu_permission
(
    id            int8 generated by default as identity primary key,
    menu_id       int8      not null, -- 菜单ID
    permission_id int8      not null, -- 接口权限ID
    create_time   timestamp not null, -- '创建时间',
    update_time   timestamp not null  -- '最近更新时间'
);
comment on table sys_menu_permission is '前端菜单接口权限关联表';
comment on column sys_menu_permission.menu_id is '菜单ID';
comment on column sys_menu_permission.permission_id is '接口权限ID';
comment on column sys_menu_permission.create_time is '创建时间';
comment on column sys_menu_permission.update_time is '最近更新时间';


-- 前端菜单角色关联表
DROP TABLE IF EXISTS sys_role_menu;
CREATE TABLE sys_role_menu
(
    id          int8 generated by default as identity primary key,
    menu_id     int8      not null, -- 菜单ID
    role_id     int8      not null, -- 角色ID
    create_time timestamp not null, -- '创建时间',
    update_time timestamp not null  -- '最近更新时间'
);
comment on table sys_role_menu is '前端菜单角色关联表';
comment on column sys_role_menu.menu_id is '菜单ID';
comment on column sys_role_menu.role_id is '角色ID';
comment on column sys_role_menu.create_time is '创建时间';
comment on column sys_role_menu.update_time is '最近更新时间';